name: paybiz
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Added dependencies
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  tutorial_coach_mark: ^1.2.12

  # Existing dependencies
  cloud_firestore: ^5.6.0
  crypto: ^3.0.6
  fluttertoast: ^8.2.5
  animated_splash_screen: ^1.3.0
  intl: ^0.20.1
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
